spring.datasource.url: jdbc:mysql://localhost:3306/blog?serverTimezone=Europe/Moscow&useSSL=false
spring.datasource.username: root
spring.datasource.password: Qwe123456!
spring.jpa.hibernate.ddl-auto: validate
